### ISSUE TITLE
Unable to start docker-volume-glusterfs daemon

### ISSUE THREAD

**Issue by MikeVL** [calavera/docker-volume-glusterfs#6]
I`am try to start docker volume daemon, but after the start of the console is not the message "Listening on ..."
<img width="970" alt="2015-11-03 11 50 27" src="https://cloud.githubusercontent.com/assets/118285/10904055/1d9912a2-8221-11e5-885c-3f5dc6dc5d78.png">

```
11:45 root@gluster-msk3 ➜  ~  glusterfs --version
glusterfs 3.4.7 built on Apr  9 2015 02:51:29
```

**Comment by calavera** [comment]
mmmm that message might have gone away with some changes, did you try run a container using the driver?

**Comment by MikeVL** [comment]
Sorry, It`s works!
