### ISSUE TITLE
Build impossible since docker removed docker socket

### ISSUE THREAD

**Issue by h4wkmoon** [calavera/docker-volume-glusterfs#8]
Check this commit : 
https://github.com/docker/docker/commit/8e034802b7ad92a29f08785e553415adcd1348a3

Since that moment, this command fails : 
go get github.com/calavera/docker-volume-glusterfs

**Comment by h4wkmoon** [comment]
Maybe docker-volume-glusterfs should move from dkvolume to the new plugins-helpers.

**Comment by calavera** [comment]
this should be fixed now, thanks!

**Comment by h4wkmoon** [comment]
It"s always a pleasure to help.
Be sure to double check my contributions. I'm far from a Go developper..

2016-01-05 20:52 GMT+01:00 David Calavera <notifications@github.com>:

> this should be fixed now, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calavera/docker-volume-glusterfs/issues/8#issuecomment-169110701>
> .
>



-- 
Linux: Rejoins-nous, nous sommes déjà 11.
